services:
    marcovo.hideBBcode.listener:
        class: marcovo\hideBBcode\event\listener
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@template'
            - '@config'
            - '@controller.helper'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
